
import { MobSFService } from '../api/mobsf-service.js';
import { FBHBotClient } from '../infrastructure/external/fbhbot-client.js';
import { HexStrikeManager } from './hexstrike-manager.js';
import { AISwarm } from '../../../fbhbot/src/services/ai_swarm.js'; // Assuming shared codebase access or need to duplicate/import logic
import fs from 'fs';
import path from 'path';

export class ReportEngine {
    private mobsf: any; // Types are a bit loose across boundaries, keeping flexible
    private fbhbot: any;
    private hexstrike: HexStrikeManager;
    private ai: AISwarm; // We might need to instantiate this or use a simplified AI client

    constructor(hexstrike: HexStrikeManager) {
        this.hexstrike = hexstrike;
        // In a real integrated mono-repo we'd inject these properly
        // For now we might need to fetch data directly or use static methods if they exist
        // or just assume we receive the data payloads to generate the report
    }

    /**
     * Generates a comprehensive "Shadow Report"
     */
    async generateReport(target: string, data: {
        mobsfData?: any;
        fbhbotData?: any;
        hexstrikeData?: any;
        logicData?: any;
    }): Promise<{ markdown: string; pdfPath: string }> {

        const timestamp = new Date().toISOString().split('T')[0];
        const reportId = `REP-${Buffer.from(target).toString('hex').substring(0, 6).toUpperCase()}-${timestamp}`;

        console.log(`[ReportEngine] Generating Shadow Report ${reportId} for ${target}`);

        // 1. Construct the context for the AI
        let context = `# Executive Intelligence Report: ${target}\n`;
        context += `**Date**: ${new Date().toLocaleString()}\n`;
        context += `**Classification**: SOVEREIGN ONLY // EYES ONLY\n\n`;

        if (data.mobsfData) {
            context += `## Mobile Security Analysis (MobSF)\n`;
            context += `- **Score**: ${data.mobsfData.security_score || 'N/A'}/100\n`;
            context += `- **Critical Issues**: ${data.mobsfData.high_issues || 0}\n`;
            context += `- **Trackers**: ${data.mobsfData.trackers || 0}\n\n`;
        }

        if (data.fbhbotData) {
            context += `## Deep Static Analysis (FBHBot)\n`;
            // Summarize FBHBot findings
            if (data.fbhbotData.secrets && data.fbhbotData.secrets.length > 0) {
                context += `- **Secrets Discovered**: ${data.fbhbotData.secrets.length}\n`;
            }
        }

        if (data.hexstrikeData) {
            context += `## Infrastructure Reconnaissance (HexStrike)\n`;
            context += `- **Vulnerabilities**: ${data.hexstrikeData.total_vulnerabilities || 0}\n`;
            // Add tool summary
        }

        // --- IMPACT ESCALATION (Phase 11) ---
        // Simple logic to simulate the Escalator python behavior in TS
        // If we detect "Production" keywords or PII data types, we boost the tone.
        const isProdCandidate = target.match(/(prod|live|platform|api\.|www\.)/i);
        let escalationNote = "";

        if (isProdCandidate) {
            context += `\n>> **ESCALATION**: Target appears to be PRODUCTION environment. Severity boosted.\n`;
            escalationNote = "> ⚠️ **CRITICAL CONTEXT**: This target appears to be a **PRODUCTION** environment. Findings should be treated with maximum urgency.";
        }

        if (data.mobsfData?.trackers?.length > 5) {
            context += `\n>> **ESCALATION**: High number of trackers detected, privacy risk elevated.\n`;
            if (!escalationNote) escalationNote = "> ⚠️ **PRIVACY ALERT**: Excessive user tracking detected.";
        }
        // ------------------------------------

        if (data.logicData) {
            context += `## Business Logic Analysis\n`;
            context += `- **Workflow ID**: ${data.logicData.workflow?.id}\n`;
        }

        // 2. Draft the Executive Summary
        // Ideally we call the AI Agent here. For this implementation layer, we'll template it 
        // effectively to ensure robustness if the Python bridge isn't perfect for this specific task.

        let markdown = `
# 🕵️‍♂️ SHADOW REPORT: ${target.toUpperCase()}
> **CONFIDENTIALITY PROTOCOL**: RED
> **GENERATED BY**: FBHBOT SOVEREIGN SUITE
${escalationNote ? '\n' + escalationNote + '\n' : ''}
---

## 1. EXECUTIVE SUMMARY
Recent autonomous scanning of **${target}** has revealed a composite security posture. 
${data.mobsfData ? `Mobile application analysis indicates a security score of **${data.mobsfData.security_score}/100**.` : ''}
${data.hexstrikeData ? `Infrastructure probing detected **${data.hexstrikeData.total_vulnerabilities}** potential vulnerabilities across the attack surface.` : ''}

## 2. KEY FINDINGS

### 📱 Mobile Vector
${data.mobsfData ? `
- **App Name**: ${data.mobsfData.file_name || 'Unknown'}
- **Package**: ${data.mobsfData.package_name || 'Unknown'}
- **Critical Risks**: ${data.mobsfData.high_issues}
` : '_No mobile data provided._'}

### ☁️ Infrastructure Vector
${data.hexstrikeData ? `
- **Tools Deployed**: ${data.hexstrikeData.tools_executed?.map((t: any) => t.tool).join(', ')}
- **Critical Findings**:
${data.hexstrikeData.tools_executed?.filter((t: any) => t.vulnerabilities_found > 0).map((t: any) => `  - **${t.tool.toUpperCase()}**: ${t.vulnerabilities_found} issues`).join('\n') || '  - None detected.'}
` : '_No infrastructure data provided._'}

### 🧠 Logic & API Vector
${data.logicData ? `
- **Workflow Strategy**: ${data.logicData.workflow?.strategy || 'N/A'}
- **Steps Generated**: ${data.logicData.workflow?.steps?.length || 0}
` : '_No logic analysis data provided._'}

## 3. REMEDIATION STRATEGY
1. **Immediate Action**: Address all Critical findings (Red) identified in the Infrastructure Scan.
2. **Mobile Hardening**: Review shared secrets and minimize permissions as flagged in the MobSF report.
3. **Logic Review**: Verify the business logic workflows manually for false positives.

---
*Generated by FBHBot Sovereign Intel System*
`;

        // 3. Save to disk
        const reportsDir = path.join(process.cwd(), 'reports');
        if (!fs.existsSync(reportsDir)) {
            fs.mkdirSync(reportsDir);
        }

        const fileName = `SHADOW_REPORT_${target.replace(/[^a-z0-9]/gi, '_').toUpperCase()}_${Date.now()}.md`;
        const filePath = path.join(reportsDir, fileName);

        fs.writeFileSync(filePath, markdown);
        console.log(`[ReportEngine] Report saved to ${filePath}`);

        return {
            markdown,
            pdfPath: filePath // Returning MD path for now, frontend can render or we can add PDF conversion later
        };
    }
}
