import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { Construction, ShieldAlert, Search, FileText, ArrowLeft, Clock } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
const UnderConstruction = ({ title, description, icon: Icon }) => {
    const navigate = useNavigate();
    return (_jsx("div", { className: "flex flex-col items-center justify-center min-h-[70vh] p-8 text-center animate-in fade-in duration-700", children: _jsxs(motion.div, { initial: { y: 20, opacity: 0 }, animate: { y: 0, opacity: 1 }, className: "max-w-md space-y-8", children: [_jsxs("div", { className: "relative inline-block", children: [_jsx("div", { className: "p-8 bg-primary/5 border border-primary/20 rounded-full", children: _jsx(Icon, { size: 64, className: "text-primary opacity-50" }) }), _jsx("div", { className: "absolute -bottom-2 -right-2 p-2 bg-slate-950 border border-orange-500/50 rounded-lg shadow-2xl", children: _jsx(Construction, { size: 20, className: "text-orange-500 animate-pulse" }) })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("div", { className: "flex justify-center", children: _jsx(Badge, { variant: "outline", className: "border-orange-500/30 text-orange-500 bg-orange-500/5 text-[10px] uppercase font-mono px-2", children: "Deployment in Progress" }) }), _jsx("h1", { className: "text-3xl font-bold tracking-tight text-white", children: title }), _jsx("p", { className: "text-slate-500 text-sm leading-relaxed", children: description })] }), _jsx(Card, { className: "border-border/40 bg-slate-900/40 backdrop-blur-sm shadow-xl", children: _jsx(CardContent, { className: "p-6", children: _jsxs("div", { className: "flex items-center gap-4 text-left", children: [_jsx("div", { className: "p-3 bg-primary/10 rounded-xl border border-primary/20 text-primary", children: _jsx(Clock, { size: 24 }) }), _jsxs("div", { children: [_jsx("h4", { className: "text-sm font-bold text-white uppercase tracking-widest", children: "Estimated Uplink" }), _jsx("p", { className: "text-xs text-slate-400", children: "Phase 9: Final Deployment Schedule (T-Minus 48h)" })] })] }) }) }), _jsx("div", { className: "pt-4", children: _jsxs(Button, { variant: "ghost", onClick: () => navigate(-1), className: "text-slate-500 hover:text-white gap-2 uppercase text-[10px] font-bold tracking-widest", children: [_jsx(ArrowLeft, { size: 14 }), " Revert to HQ"] }) })] }) }));
};
export default UnderConstruction;
//# sourceMappingURL=UnderConstruction.js.map