"""
Report Generator Module
Creates professional bug bounty reports
"""
from pathlib import Path
from typing import Dict, List, Any
from datetime import datetime
from rich.console import Console

console = Console()


class ReportGenerator:
    """
    Generates bug bounty reports in various formats
    """
    
    def __init__(self, output_dir: Path):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_report(
        self,
        format_type: str,
        static_results: Dict,
        dynamic_results: Dict,
        pocs: List[Dict],
        ai_results: Dict
    ) -> Path:
        """
        Generate report in specified format
        
        Args:
            format_type: 'hackerone', 'bugcrowd', or 'markdown'
            static_results: Static analysis findings
            dynamic_results: Dynamic analysis findings
            pocs: Generated PoCs
            ai_results: AI analysis results
            
        Returns:
            Path to generated report
        """
        if format_type == 'hackerone':
            return self._generate_hackerone_report(static_results, dynamic_results, pocs, ai_results)
        elif format_type == 'bugcrowd':
            return self._generate_bugcrowd_report(static_results, dynamic_results, pocs, ai_results)
        elif format_type == 'markdown':
            return self._generate_markdown_report(static_results, dynamic_results, pocs, ai_results)
        else:
            raise ValueError(f"Unsupported format: {format_type}")
    
    def _generate_hackerone_report(self, static, dynamic, pocs, ai) -> Path:
        """Generate HackerOne-formatted report"""
        report_path = self.output_dir / "hackerone_report.md"
        
        # Compile findings
        all_findings = self._compile_findings(static, dynamic, ai)
        
        # Calculate severity
        severity = self._calculate_severity(all_findings)
        
        report = f"""# Security Vulnerability Report

## Summary

**Severity**: {severity}  
**Asset**: [Target Application]  
**Vulnerability Type**: Multiple Security Issues  
**Discovered**: {datetime.now().strftime('%Y-%m-%d')}

## Description

During security testing of the target application, multiple security vulnerabilities were identified using automated and
    and manual analysis techniques.

## Impact

The identified vulnerabilities could allow an attacker to:

"""
        
        # Add impacts
        impacts = self._generate_impacts(all_findings)
        for impact in impacts:
            report += f"- {impact}\n"
        
        report += """
## Steps to Reproduce

### Prerequisites
- Target application installed
- Testing device/emulator

### Reproduction Steps

"""
        
        # Add reproduction steps for top findings
        for i, finding in enumerate(all_findings[:5], 1):
            report += f"#### Finding {i}: {finding.get('title', 'Security Issue')}\n\n"
            report += f"**Severity**: {finding.get('severity', 'medium').upper()}\n\n"
            report += "Steps:\n"
            report += f"1. {finding.get('description', 'See technical details')}\n"
            report += f"2. Observe the security issue\n\n"
        
        # Add PoCs
        if pocs:
            report += "## Proof of Concept\n\n"
            for i, poc in enumerate(pocs[:3], 1):
                if poc.get('validated'):
                    report += f"### PoC {i}: {poc.get('title', 'Exploit')}\n\n"
                    report += "```python\n"
                    report += poc.get('code', '# PoC code here')
                    report += "\n```\n\n"
        
        report += """
## Remediation

To fix these vulnerabilities:

"""
        
        # Add remediation steps
        remediations = self._generate_remediations(all_findings)
        for remediation in remediations:
            report += f"- {remediation}\n"
        
        report += """
## References

- OWASP Mobile Top 10
- CWE Database
- Security Best Practices

---

*Report generated by SecuritySentinel Automated Bug Bounty Hunter*
"""
        
        report_path.write_text(report)
        return report_path
    
    def _generate_bugcrowd_report(self, static, dynamic, pocs, ai) -> Path:
        """Generate Bugcrowd-formatted report"""
        report_path = self.output_dir / "bugcrowd_report.md"
        
        all_findings = self._compile_findings(static, dynamic, ai)
        severity = self._calculate_severity(all_findings)
        
        report = f"""# Vulnerability Disclosure

## Vulnerability Information

**Title**: Multiple Security Vulnerabilities in Mobile Application  
**Severity**: {severity}  
**CWE**: Multiple  
**CVSS Score**: {self._calculate_cvss(all_findings)}

## Technical Details

"""
        
        for i, finding in enumerate(all_findings[:10], 1):
            report += f"### {i}. {finding.get('title', 'Security Issue')}\n\n"
            report += f"**Type**: {finding.get('type', 'Security Misconfiguration')}\n"
            report += f"**Severity**: {finding.get('severity', 'medium').upper()}\n\n"
            report += f"{finding.get('description', 'Security vulnerability detected')}\n\n"
        
        report += "## Exploitation\n\n"
        report += f"Total validated PoCs: {len([p for p in pocs if p.get('validated')])}\n\n"
        
        report += "## Impact Assessment\n\n"
        impacts = self._generate_impacts(all_findings)
        for impact in impacts:
            report += f"- {impact}\n"
        
        report += "\n---\n\n*Generated by SecuritySentinel*\n"
        
        report_path.write_text(report)
        return report_path
    
    def _generate_markdown_report(self, static, dynamic, pocs, ai) -> Path:
        """Generate comprehensive markdown report"""
        report_path = self.output_dir / "technical_report.md"
        
        all_findings = self._compile_findings(static, dynamic, ai)
        
        report = f"""# SecuritySentinel Security Assessment Report

**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**Tool**: SecuritySentinel v5.0  
**Analysis Type**: Automated Security Testing

---

## Executive Summary

Total findings: {len(all_findings)}

### Severity Breakdown

"""
        
        severity_counts = {'critical': 0, 'high': 0, 'medium': 0, 'low': 0}
        for finding in all_findings:
            sev = finding.get('severity', 'low').lower()
            severity_counts[sev] = severity_counts.get(sev, 0) + 1
        
        report += f"- **Critical**: {severity_counts['critical']}\n"
        report += f"- **High**: {severity_counts['high']}\n"
        report += f"- **Medium**: {severity_counts['medium']}\n"
        report += f"- **Low**: {severity_counts['low']}\n\n"
        
        report += "## Static Analysis Results\n\n"
        for analyzer, results in static.items():
            count = len(results) if isinstance(results, list) else 0
            report += f"### {analyzer.title()}\n\n"
            report += f"Findings: {count}\n\n"
        
        report += "## Dynamic Analysis Results\n\n"
        for analyzer, results in dynamic.items():
            count = len(results) if isinstance(results, list) else 0
            report += f"### {analyzer.title()}\n\n"
            report += f"Findings: {count}\n\n"
        
        report += f"## AI Analysis\n\n"
        report += f"Risk Score: {ai.get('risk_score', 0)}/10\n\n"
        report += f"AI Findings: {ai.get('findings_count', 0)}\n\n"
        
        report += f"## Proof of Concepts\n\n"
        report += f"Total PoCs: {len(pocs)}\n"
        report += f"Validated: {len([p for p in pocs if p.get('validated')])}\n\n"
        
        report += "---\n\n*End of Report*\n"
        
        report_path.write_text(report)
        return report_path
    
    def _compile_findings(self, static, dynamic, ai) -> List[Dict]:
        """Compile all findings into single list"""
        findings = []
        
        for category in [static, dynamic]:
            for analyzer, results in category.items():
                if isinstance(results, list):
                    findings.extend(results)
        
        if ai.get('findings'):
            findings.extend(ai['findings'])
        
        return findings
    
    def _calculate_severity(self, findings: List[Dict]) -> str:
        """Calculate overall severity"""
        if any(f.get('severity') == 'critical' for f in findings):
            return "Critical"
        elif any(f.get('severity') == 'high' for f in findings):
            return "High"
        elif any(f.get('severity') == 'medium' for f in findings):
            return "Medium"
        else:
            return "Low"
    
    def _calculate_cvss(self, findings: List[Dict]) -> float:
        """Calculate CVSS score"""
        # Simplified CVSS calculation
        severity_scores = {'critical': 9.5, 'high': 7.5, 'medium': 5.0, 'low': 2.5}
        
        if not findings:
            return 0.0
        
        max_score = max(
            severity_scores.get(f.get('severity', 'low').lower(), 2.5)
            for f in findings
        )
        
        return max_score
    
    def _generate_impacts(self, findings: List[Dict]) -> List[str]:
        """Generate impact statements"""
        impacts = set()
        
        for finding in findings:
            if 'secret' in finding.get('type', '').lower():
                impacts.add("Access sensitive credentials and API keys")
            if 'sql' in finding.get('type', '').lower():
                impacts.add("Execute arbitrary SQL queries")
            if 'webview' in finding.get('type', '').lower():
                impacts.add("Execute JavaScript in WebView context")
            if 'intent' in finding.get('type', '').lower():
                impacts.add("Manipulate app behavior via intent injection")
        
        return list(impacts) if impacts else ["Compromise application security"]
    
    def _generate_remediations(self, findings: List[Dict]) -> List[str]:
        """Generate remediation recommendations"""
        remediations = set()
        
        for finding in findings:
            if finding.get('remediation'):
                remediations.add(finding['remediation'])
        
        return list(remediations) if remediations else ["Follow security best practices"]
