#!/usr/bin/env python3
"""
anisette_bridge.py — AnisetteV3 / ADI Token Bridge Server
Runs on Mac at 192.168.64.1:6969

PURPOSE:
  Apple servers require X-Apple-I-MD and X-Apple-I-MD-M headers for authenticated
  requests (Apple ID, App Store, iCloud). These are generated by the ADI protocol
  (Apple Device Identity) in the `adid` daemon, which derives device-bound tokens
  from FairPlay IOKit via the ADI Client entitlement.

  Since VPhone's adid fails to generate valid ADI tokens (no real FairPlay hardware),
  this bridge:
  1. Provides Anisette data captured from a real device (or an AnisetteV3 server)
  2. Serves it to the VPhone over HTTP so our LaunchDaemon hook can inject them
  3. Acts as a local AnisetteV3-compatible server endpoint

ANISETTE DATA STRUCTURE (X-Apple-I-MD headers):
  X-Apple-I-MD:         Base64-encoded "MachineData" — device-specific OTP token
  X-Apple-I-MD-M:       Base64-encoded "MachineDataMessage" — routing key
  X-Apple-I-MD-LU:      Apple ID local user
  X-Apple-I-MD-RINFO:   Routing info (integer)

USAGE:
  On Mac:   python3 anisette_bridge.py
  On VPhone: curl http://192.168.64.1:6969/anisette
  
  To fill with REAL device Anisette data, set ANISETTE_SERVER or
  expose your own AnisetteV3 server (e.g. https://github.com/nickcoutsos/anisette-v3-server)
"""

import http.server
import json
import os
import time
import base64
import hashlib
import struct
import uuid
import subprocess
from datetime import datetime, timezone

# ─── CONFIGURATION ──────────────────────────────────────────────────────────
LISTEN_HOST = "0.0.0.0"
LISTEN_PORT = 6969

# Real device Anisette data from RustA12-bypass iPhone 12,5
# These are placeholder headers — replace with real captured values
# from an AnisetteV3 server or from a real iPhone 12,5 session.
# Real capture: pymobiledevice3 apps install-developer-image  (triggers ADI generation)
SPOOFED_DEVICE_ID = "A3695F3C-B64F-11F0-9F73-6E4CBABDD792"  # from MobileGestalt UDID
SPOOFED_SERIAL    = "VPHONE12MAX01"
SPOOFED_MODEL     = "iPhone12,5"
SPOOFED_BOARD     = "D431AP"

# AnisetteV3 external server (optional — if set, proxies to this)
ANISETTE_SERVER = os.environ.get("ANISETTE_SERVER", "")

# ─── ADI Token Generation (Placeholder / Simulated) ─────────────────────────
def generate_machine_data(device_id: str, timestamp: int) -> str:
    """
    Generate a simulated MachineData token.
    Real tokens are generated by the ADI protocol inside fairplayd via IOKit.
    This is a PLACEHOLDER — real tokens must be sourced from:
      1. A real iPhone 12,5 with pymobiledevice3
      2. An AnisetteV3 server (Rust binary)
      3. Captured from mitmdump traffic
    """
    # Hash device_id + timestamp into 128 bytes (simulated OTP structure)
    h = hashlib.sha512(f"{device_id}:{timestamp}".encode()).digest()
    return base64.b64encode(h).decode()

def generate_machine_data_message(device_id: str, timestamp: int) -> str:
    """
    Generate a simulated MachineDataMessage (routing key).
    """
    h = hashlib.sha256(f"MDM:{device_id}:{timestamp}".encode()).digest()
    return base64.b64encode(h).decode()

def get_anisette_headers() -> dict:
    """
    Fetch real Anisette headers from external AnisetteV3 server, or generate simulated ones.
    """
    if ANISETTE_SERVER:
        try:
            import urllib.request
            with urllib.request.urlopen(f"{ANISETTE_SERVER}/anisette", timeout=5) as resp:
                data = json.loads(resp.read())
                return data
        except Exception as e:
            print(f"[anisette_bridge] External server failed: {e}, using simulated")

    ts = int(time.time() * 1000)
    return {
        "X-Apple-I-MD":           generate_machine_data(SPOOFED_DEVICE_ID, ts),
        "X-Apple-I-MD-M":         generate_machine_data_message(SPOOFED_DEVICE_ID, ts),
        "X-Apple-I-MD-RINFO":     "17106176",
        "X-Apple-I-SF-Rv":        "1",
        "X-Apple-I-TimeZone":     "UTC",
        "X-Apple-I-Client-Time":  datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "X-Apple-Locale":         "en_US",
        "X-MMe-Client-Info":      f"<{SPOOFED_MODEL}> <iPhone OS;26.1;23B85> <com.apple.AuthKit/1 (com.apple.iCloud/7.21)>",
        "X-Apple-I-MD-LU":        base64.b64encode(SPOOFED_DEVICE_ID.encode()).decode(),
        # Meta for debugging
        "_device_id":  SPOOFED_DEVICE_ID,
        "_model":      SPOOFED_MODEL,
        "_board":      SPOOFED_BOARD,
        "_timestamp":  ts,
        "_note":       "SIMULATED — replace with real AnisetteV3 server output",
    }

# ─── HTTP Server ─────────────────────────────────────────────────────────────
class AnisetteHandler(http.server.BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        print(f"[{datetime.now().strftime('%H:%M:%S')}] {self.client_address[0]} {format % args}")

    def do_GET(self):
        if self.path == "/anisette" or self.path == "/anisette/v3":
            headers_data = get_anisette_headers()
            body = json.dumps(headers_data, indent=2).encode()
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", len(body))
            self.end_headers()
            self.wfile.write(body)

        elif self.path == "/status":
            body = json.dumps({
                "status": "running",
                "model": SPOOFED_MODEL,
                "board": SPOOFED_BOARD,
                "device_id": SPOOFED_DEVICE_ID,
                "external_server": ANISETTE_SERVER or "none",
            }, indent=2).encode()
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", len(body))
            self.end_headers()
            self.wfile.write(body)

        elif self.path == "/provision":
            # Endpoint for VPhone to request ADI provisioning (OTP generation)
            # In production: triggers adid's XPC call to fairplayd and returns the result
            body = json.dumps({
                "status": "not_implemented",
                "note": "Provision endpoint requires real fairplayd XPC intercept — see Phase 2",
            }, indent=2).encode()
            self.send_response(501)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", len(body))
            self.end_headers()
            self.wfile.write(body)

        else:
            self.send_response(404)
            self.end_headers()

    def do_POST(self):
        """Accept captured Anisette data pushed from VPhone or real device."""
        if self.path == "/anisette/upload":
            length = int(self.headers.get("Content-Length", 0))
            body = self.rfile.read(length)
            try:
                data = json.loads(body)
                # Save to disk for later use
                with open("/tmp/captured_anisette.json", "w") as f:
                    json.dump(data, f, indent=2)
                print(f"[anisette_bridge] Captured Anisette data saved to /tmp/captured_anisette.json")
                self.send_response(200)
                self.end_headers()
                self.wfile.write(b'{"status":"saved"}')
            except Exception as e:
                self.send_response(400)
                self.end_headers()
                self.wfile.write(f'{{"error":"{e}"}}'.encode())
        else:
            self.send_response(404)
            self.end_headers()


if __name__ == "__main__":
    print(f"╔══════════════════════════════════════════════════════╗")
    print(f"║  AnisetteV3 Bridge  —  http://0.0.0.0:{LISTEN_PORT}    ║")
    print(f"║  Device: {SPOOFED_MODEL} / {SPOOFED_BOARD}              ║")
    print(f"║  UDID:   {SPOOFED_DEVICE_ID[:22]}...  ║")
    if ANISETTE_SERVER:
        print(f"║  Proxy → {ANISETTE_SERVER[:42]}  ║")
    else:
        print(f"║  Mode:  SIMULATED (set ANISETTE_SERVER for real)    ║")
    print(f"╚══════════════════════════════════════════════════════╝")
    print(f"")
    print(f"Endpoints:")
    print(f"  GET  /anisette       → Anisette headers JSON")
    print(f"  GET  /status         → Bridge status")
    print(f"  POST /anisette/upload → Upload captured real Anisette data")
    print(f"")

    server = http.server.HTTPServer((LISTEN_HOST, LISTEN_PORT), AnisetteHandler)
    print(f"Listening on {LISTEN_HOST}:{LISTEN_PORT} ...")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nBridge stopped.")
